sudo: required
services:
  - docker

before_install:
  - docker build -t e3cd/docker-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true e3cd/docker-travis-aws npm run test -- --watchAll=false
