sudo: required
services:
  - docker

before_install:
  - docker build -t e3cd/docker-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true e3cd/docker-travis-aws npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-585043354208"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
